apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: proof-of-concept
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: "kubedevio/web-color:blue"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: "0.5"
              memory: 512Mi
