apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: kubedevio/web-color:blue
    resources:
    ports:
    - name: http
      containerPort: 80
      protocol: TCP